apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: ubuntu/postgres:edge
        env:
        - name: POSTGRES_PASSWORD
          value: "mysecret" # TODO: handle secret properly. (This is to _set_ the password when initializing the db)
        volumeMounts:
        - name: postgres-config-volume
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        - name: postgres-data
          mountPath: /var/lib/postgresql/
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: observability
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    name: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: observability
data:
  postgresql.conf: |-
    listen_addresses = '*'
---
